# Project
version=10.0.0
group=com.mrbysco.instrumentalmobs

# Common
minecraft_version=1.21.11
neoform_version=1.21.11-20251209.172050
mixin_version=0.16.5+mixin.0.8.7
mixinextras_version=0.5.0

# NeoForge
neo_version=21.11.38-beta
parchment_minecraft_version=1.21.11
parchment_mapping_version=2025.12.20

# Fabric
fabric_version=0.141.3+1.21.11
fabric_loader_version=0.18.4
cloth_config_version=21.11.153
mod_menu_version=17.0.0-beta.2

# Mod options
mod_name=InstrumentalMobs
mod_author=Mrbysco
mod_id=instrumentalmobs

#Publishing
curseforge_id=299602
modrinth_id=4uT1MZts

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false