# Project
version=8.0.0
group=com.mrbysco.instrumentalmobs

# Common
minecraft_version=1.21.5

# NeoForge
neo_version=21.5.58-beta
neogradle.subsystems.parchment.minecraftVersion=1.21.5
neogradle.subsystems.parchment.mappingsVersion=2025.04.19
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.121.0+1.21.5
fabric_loader_version=0.16.14
cloth_config_version=18.0.145
mod_menu_version=14.0.0-rc.2

# Mod options
mod_name=InstrumentalMobs
mod_author=Mrbysco
mod_id=instrumentalmobs

#Publishing
curseforge_id=299602
modrinth_id=4uT1MZts

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false