modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/InstrumentalMobs/issues"
license="MIT"

[[mods]]
modId="instrumentalmobs"
version="${file.jarVersion}"
displayName="Instrumental Mobs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/instrumental-mobs"
authors="Mrbysco"
description='''
Adds instrumental mobs to Minecraft.
'''
credits="Darkosto's chat for inspiring me"
[[dependencies.instrumentalmobs]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.instrumentalmobs]]
modId="forge"
mandatory=true
versionRange="[41.0.94,)"
ordering="NONE"
side="BOTH"